-- Unique items are registered using their name, as this is way moer future proof
-- Otherwise, the item uses its key if the map has multiple instances, or if more instances can be easily gotten
locationKeys = {
    ["grock"]                  = "Green Fire Rock",
    ["blackrock"]              = "Hell Rock",
    ["argemia_13"]             = "White Argemia Plush",
    ["argemia_12"]             = "Black Argemia Plush",
    ["lambert"]                = "Lambert Plush",
    ["kerfuro"]                = "Kerfur-Omega",
    ["kerfurO_r"]              = "Kerfur-Omega",
    ["kerfurO_p"]              = "Kerfur-Omega",
    ["kerfurO_nc"]             = "Kerfur-Omega",

    ["argemia"]                = "Red Argemia Plush",
    ["argemia_0"]              = "Green Argemia Plush",
    ["argemia_1"]              = "Blue Argemia Plush",
    ["argemia_9"]              = "Yellow Argemia Plush",
    ["argemia_10"]             = "Cyan Argemia Plush",
    ["argemia_11"]             = "Magenta Argemia Plush",

    ["abplush"]                = "Antibreather Plush",
    ["eriePlush"]              = "Erie Plush",
    ["candleh"]                = "Librarian Candle",
    ["moniquePlush"]           = "Monique Plush",
    ["dreamplush"]             = "Dream Plush",
    ["wendplush"]              = "Furfur Plush",
    ["yulegoat"]               = "Yule Straw Goat",

    ["UK3WDv9SER3RICHHhSjcVw"] = "Ventilation Unit Sandwich",
    ["Yk5ywVQJylnraITkXRavAw"] = "Basement Stairs Sandwich",
    ["Fssy2fw_pVZJT9AAAT762w"] = "Abandoned Shack Sandwich",
    ["A4Cd_GpurH4UIrcn_fux7A"] = "Stonehenge Sandwich",
    ["sUu6KGMQHyBBYas-5MTfzA"] = "Radio Tower Pole Sandwich",
    ["0JvEG1LrlK_JLRl9hcJDhQ"] = "Bathroom Sandwich",
    ["T1P9Ugi2aoY2ChDrSFfsVA"] = "Oven Sandwich",
    ["gw3M6ymIULvmEbqyoERA_g"] = "Alpha Server Sandwich",
    ["WFqF3_M--Grl8I3o9GhtrQ"] = "Garage Roof Sandwich",
    ["-3oFvEGnxOystPKo5_KpcQ"] = "Radrar Dome Sandwich",
    ["HDZ8Wl5oOG2L686OxK2GsA"] = "River Sandwich",
    ["rr8ev1YThaCqcZoSgKr7Cw"] = "TR2 Sandwich",
    ["wLPERlBsmvrMdVGokAVN7Q"] = "Lake Log Sandwich",
    ["ihZeNFX1OHRjoAEFNdxygg"] = "Juliett Sandwich",
    ["wNbz7cDzg8rFVFS7ALJJ6g"] = "Whiskey Sandwich",
    ["AxQjo8xDObq_BWEzwfzJVA"] = "Rozital Ship Sandwich",
    ["1jX1ivoN3cilJZD8YCkb0A"] = "Fenced Trees Sandwich",
    ["h8wx0DoYXl-SSGisoXEmCw"] = "Hole Sandwich",
    ["jUUnzaigTvaY0f5ZUUYBcA"] = "Cave Entrance Sandwich",
    ["LdcVGn_kKW0Wske-ZTiYXA"] = "Cave Mushroom Pile Sandwich",
    ["8PlzsKuYYsYI5JcgTleyrw"] = "Buried Sandwich",

    ["szdjIdH4EI53gEbFgozcFQ"] = "Alpha Roof Tile",
    ["l3vFeFqy4hbgQBoLZr6tag"] = "CR3 Tile",
    ["YwJxqxtk66BZltG39GPWqw"] = "Alpha Bridge Tile",
    ["0txqL0LV66sWvzXyDq8aYQ"] = "Xray Tile",
    ["o4v4sTtwi3meUAX0reBhBQ"] = "TR2 Tile",
    ["TfSIooU8Ja_tk7GbvqBF5Q"] = "Hole Tile",
    ["S94g2eAncqKNR9hVAIWUAA"] = "Sierra Tile",
    ["Q3nFghvUT2BW5wiV0GzbOQ"] = "Stolas Church Tile",
    ["dg54FV4RgBB81CKjkl9dpg"] = "Green Cabinet Tile",

    ["6WY8xEH76bycYZhRQJTk_A"] = "Basement Skull",
    ["z36auTahauMovYKZUpobeg"] = "Stonehenge Skull",
    ["0D0UJl7cn5E9IW2SN3620w"] = "Gravel Circle Skull",
    ["XhMXkMqfQuKcE2odD4zJ5Q"] = "Radioactive Capsule Skull",
    ["XY48X55WfgiZzC8GsJXm4A"] = "Cave Entrance Skull",
    ["A3MY_r9QjL5k8D8o3KUPMQ"] = "Buried Box Skull",
    ["zIeF6stogF2KJptQJzEUWg"] = "Rozital Capsule Skull",

    ["y7Bj1dIPKB1tIY9YtKkaiQ"] = "Ball Joints Box 1",
    ["Q5i6p9eOBH13i7euRTuVhA"] = "Ball Joints Box 2",
    ["vO55JiBdldNVSHiAjiSQcw"] = "Ball Joints Box 3",
    ["5_2cyg0U_Pja4Tat1t-ibg"] = "Ball Joints Box 4",
    ["tlFfSjiOmgEZHpNUpCuhzg"] = "Ball Joints Box 5",
    ["ja2qS49_6KxTuO3PlDjlvw"] = "Ball Joints Box 6",

    ["uOI4KDRt27J1R61dWSyKXA"] = "TR1 Limb Joints 1",
    ["CCHozCIPrwvzN6Is38FfKA"] = "TR1 Limb Joints 2",
    ["no8QAnYv-yDEjE0xv1IP6Q"] = "TR2 Limb Joints 1",
    ["V1EBidY0fO1qePAQx1DUXA"] = "TR2 Limb Joints 2",
    ["0XPvxBWhs8lUQf-g4Krg7w"] = "TR3 Limb Joints 1",
    ["zB8P-rf1CN3mIpsail2t0w"] = "TR3 Limb Joints 2",

    ["hqwZJysFdR5lOHl_PvebNQ"] = "Bunker Keycard",
    ["1RjLKd_Ds_wEtfgYLQLzxQ"] = "Kerfur-Omega Complete Manual",
    ["kerfuro_book"]           = "Kerfur-Omega Documents Binder",
    ["kerfsp_0"]               = "Omega AI Module",
    ["fvWpNMvPGSlk3qKxoeh7fA"] = "Buried Radioactive Capsule",

    ["iuSo1BlaGkO4-gB5n-x4aw"] = "Bowtie 1",
    ["BhYXdmfVeq7XgM72dYdQ5Q"] = "Bowtie 2",
    ["W9DKwF5yHlI9WRiVI9ZW-g"] = "Glasses 1",
    ["_2xa35UTbdF-WNoWTVbgPw"] = "Glasses 2",
    ["02_V4DsnHP1LALcAB73ndA"] = "Jacket 1",
    ["2-yY6C8kk008jPWfHpzgyA"] = "Jacket 2",
    ["wCJJ3DlUH1kFZ8cDaVbcUw"] = "Badge 1",
    ["QmYjXYrl3cytb61XWMnPnQ"] = "Badge 2",

    ["vefN250Ai8DT9DGNbWRkpQ"] = "Alpha Toolbox",
    ["rDlzGGBUxXh7jq41HGJQOQ"] = "Hole Toolbox",
    ["CJA0hA9rEtxuVnSKKRebGQ"] = "Green Hatch Toolbox",
    ["fqKcbPHy9M7NoGRLMhk6RQ"] = "Deer Skull",
    ["chk-ch-s_g3_PfZhkCSxHA"] = "Medkit",
    ["G8e-1NODGF6q3qoD7MBJkA"] = "Spectogram Module",
    ["HB0M3EdnEGgYzosohcI7sQ"] = "Car Keys",
    ["NFPjHKeSnM07GnM7W73D4Q"] = "Cooking Book",
    ["JdST4317y-uNFt9EB1k_6Q"] = "Miniature Gas Can",
    ["edisylEKJm1zwO6O4UJDQw"] = "Hiking Boots",
    ["T_dFeL3A7rKqZ_AF6UDk8g"] = "Fisherman's Treasure",
    ["Oli9O-vS6yEtcR-U41xynQ"] = "Geiger Counter",
    ["CMEG2anUL3XRqgYpTazcTg"] = "EMF Detector",
    ["J8H2Pt_7Whh84q5Dxuoigg"] = "TR1 Watering Can",
    ["2fGT3pcNddQkWAErbde0wA"] = "TR1 Lighter",
    ["QVlZ8gYbHcZqkw0vwwtZbg"] = "TR1 Cigarettes",
    ["6vb_zFnIbBvszliUByxsEQ"] = "TR1 Tinfoil Hat",
    ["l6DHfQ21XnFBLQOepnb5iQ"] = "TR1 Toolbox",
    ["LddcsqrFnQyEwFMyf8eWqQ"] = "TR1 Gas Welder 1",
    ["1DNQvdhXlhKotU63j8Ileg"] = "TR1 Gas Welder 2",
    ["EapATedJQexhFnDkLtAanA"] = "TR2 Watering Can",
    ["Sz3I7lf7ImmShwVm5PjCSg"] = "TR2 Battery Charger",
    ["xKQfSSbsNniDXoPmfuDmPw"] = "TR2 Shovel",
    ["iXwfsMOrPpCkuyymBPqWOw"] = "TR3 Watering Can",
    ["hejaIqT-gbaNl_q9YaCRIw"] = "TR3 Cat Bed",
    ["Ix3tMnrNANBbN9s1g_RCaw"] = "Security Booth Shovel",
    ["Fagq6QvyBmSvDOlqzGUTjA"] = "Abandoned Shack Shovel",
    ["6PXvi0rI0CULFm_iQHGyaA"] = "Stonehenge Shovel",
    ["aLEuHsNgFr8XCXHx-DudZw"] = "Hole Gas Welder",
    ["CVOYTNa8LGNZHY7zzZP1oA"] = "Well Hook 1",
    ["pPo5pwZfpdVygU7oSgjPZw"] = "Well Hook 2",
    ["m4ulhor47zMcs6OlXW88uQ"] = "Lantern",
    ["ewkYcMrFK6QoArOPIiZQ3w"] = "Buried Cacti",
    ["UXA-whpXBUBxJGUJml7aew"] = "Wall Clock",
    ["juSEsDMAS0nc6htqC-yrOQ"] = "Radioactive Capsule Blueprint",
    ["eXT7cZxibaeS-YEjPeJLdQ"] = "Bike Helmet",
    ["massive_limestone_cube"] = "Limestone Slab",
    ["seedp_t"]                = "Seed Pack (The Thingy)",
    ["rifle"]                  = "Old Rifle",
    ["axe"]                    = "Axe",
    ["pickaxe"]                = "Pickaxe",
    ["argemug"]                = "Argemia Mug",
    ["leadpipe"]               = "Lead Pipe",
    
    ["slab_0"]                 = "Fire Tablet",
    ["slab_1"]                 = "Air Tablet",
    ["slab_2"]                 = "Water Tablet",
    ["slab_3"]                 = "Earth Tablet",
    ["ritualKnife"]            = "Ritual Knife",

    ["dingus"]                 = "Maxwell",
    ["argemwell"]              = "Argemwell",
    ["gnarpwell"]              = "Gnarpwell",
    ["eriewell"]               = "Eriewell",
    ["kerfoout_maid"]          = "Maid Outfit",
    ["llama"]                  = "Llama Plush"
}