-- Unique items are registered using their name, as this is way more future proof
-- Some items also are generated mid run, and so don't have a consistent key
-- Otherwise, the item uses its key if the map has multiple instances, or if more instances can be easily gotten
locationKeys = {
    ["grock"]                  = "Green Fire Rock",

    ["argemia"]                = "Red Argemia Plush",
    ["argemia_0"]              = "Green Argemia Plush",
    ["argemia_1"]              = "Blue Argemia Plush",
    ["argemia_9"]              = "Yellow Argemia Plush",
    ["argemia_10"]             = "Cyan Argemia Plush",
    ["argemia_11"]             = "Magenta Argemia Plush",
    ["argemia_6"]              = "Nuclear Yellow Argemia Plush",
    ["argemia_7"]              = "Nuclear Orange Argemia Plush",
    ["argemia_8"]              = "Nuclear Pink Argemia Plush",

    ["abplush"]                = "Antibreather Plush",
    ["eriePlush"]              = "Erie Plush",
    ["candleh"]                = "Librarian Candle",
    ["moniquePlush"]           = "Monique Plush",
    ["dreamplush"]             = "Dream Plush",
    ["furfurA_0"]              = "Furfur Altar Leg 1",
    ["furfurA_1"]              = "Furfur Altar Leg 2",
    ["furfurA_2"]              = "Furfur Altar Top",
    ["wendplush"]              = "Furfur Plush",
    ["yulegoat"]               = "Yule Straw Goat",

    ["NOPfAsDF7vuo1aJx0feghQ"] = "Ventilation Unit Sandwich",
    ["V66WiGC_FyF_4XX-SqEWuQ"] = "Basement Stairs Sandwich",
    ["x1vTQh78OmrOtPuvrlC-5Q"] = "Abandoned Shack Sandwich",
    ["iupjn6NdDsngsyCanS7iAw"] = "Stonehenge Sandwich",
    ["qYK5P-BUIKzreCGmRNUU9A"] = "Radio Tower Pole Sandwich",
    ["q25zprNMMKo9LVUecCX32w"] = "Bathroom Sandwich",
    ["nRx5g_E0NYl2KBP-Kwa9cQ"] = "Oven Sandwich",
    ["K2TbgRqiRCD0LZGrQMePiQ"] = "Alpha Server Sandwich",
    ["fRq55-4YClXDfXOR4uM2rA"] = "Garage Roof Sandwich",
    ["Kf9KcZJeoFhmjVS-7gAXYA"] = "Radar Dome Sandwich",
    ["kvcd2oaIZ0qSk_PfZp2AbA"] = "River Sandwich",
    ["LKRTcj1Wy6E0KHKYxky-yw"] = "TR2 Sandwich",
    ["Yqw8sZIiCQHGXBfiO_Wlbg"] = "Lake Log Sandwich",
    ["tfnTiAtNGSsF-I6sHCANkA"] = "Juliett Sandwich",
    ["WizUtPg0XH660hPnFDyk_A"] = "Whiskey Sandwich",
    ["J0_KtFf9TceIbD2B_GaMGQ"] = "Rozital Ship Sandwich",
    ["mds3Ke68L7FHJdo7TWdaLA"] = "Fenced Trees Sandwich",
    ["lIuS7P8R5ncEUX_jXqShbg"] = "Hole Sandwich",
    ["4PN09dLNFr-iFGK7VUM2WA"] = "Cave Entrance Sandwich",
    ["LiWNoPEOc0NLegZMLCZXlw"] = "Cave Mushroom Pile Sandwich",
    ["cGPKBXN-S0WjV8YGDFhILw"] = "Buried Sandwich",

    ["N5EgDSYsVKIZfiE0utaoLw"] = "Alpha Roof Tile",
    ["Vp3A4ZE5R4BZMLZvGJH4vQ"] = "CR3 Tile",
    ["7G2bb4hyQ5nt327_QJCb-g"] = "Alpha Bridge Tile",
    ["u3I7h1qrkb9Ch3vFIk01tQ"] = "Xray Tile",
    ["O4wgPBECE6FmvfUCaICM4Q"] = "TR2 Tile",
    ["Czm7hO5NiD-SHxm630iz7w"] = "Hole Tile",
    ["kN8u-h4KcDDJX7D1LlSaEg"] = "Sierra Tile",
    ["LpB9755wiv8HptOk1ztL1A"] = "Stolas Church Tile",
    ["gZVtGimlYggyVjIxLUAlig"] = "Green Cabinet Tile",

    ["RIhwy_V26OVlKvxUUAPjiw"] = "Basement Skull",
    ["LC5lPa8ahXKRLGLbk7VfYg"] = "Stonehenge Skull",
    ["q0pEAETFR9tETlMLAHj73w"] = "Gravel Circle Skull",
    ["Mc6A-0L3MaVO8h2L4bC_Sg"] = "Radioactive Capsule Skull",
    ["7-JZMlxpklXBDmTebnQ1pQ"] = "Cave Entrance Skull",
    ["-nV6O_phM93yLfw67j72BQ"] = "Buried Box Skull",
    ["FgMqHIRH-hqEllpSD52T_w"] = "Rozital Ship Skull",

    -- oldbox
    ["Z3apHQkfPfEagZifGa7R7A"] = "Ball Joints Box 1",
    ["gMjXIklxERuxgkGbPACu4w"] = "Ball Joints Box 2",
    ["H2oYDCM6U57pss3F81nGVw"] = "Ball Joints Box 3",
    ["-UyCggeZcW9Yo5tVtZ-0Lg"] = "Ball Joints Box 4",
    ["vCh-3gZnrc0CU4ara001Bg"] = "Ball Joints Box 5",
    ["z_EdET5LV8oY6jNMkr4vLA"] = "Ball Joints Box 6",

    ["OxrNNSfDyo9djWMh0-xKow"] = "TR1 Limb Joints 1",
    ["t7ujhMVCOnUOWWAEnymnSA"] = "TR1 Limb Joints 2",
    ["7agzzAgrbhZ5L58GXKzz5g"] = "TR2 Limb Joints 1",
    ["98z_vDO1sK-SN5EYc4IhSw"] = "TR2 Limb Joints 2",
    ["GpgBjjslxjWgJ2uIJlfSrQ"] = "TR3 Limb Joints 1",
    ["rWYBTM0TFAYEe_JmLlt3rQ"] = "TR3 Limb Joints 2",

    ["keycard"]                = "Bunker Keycard",
    ["kerfurManual"]           = "Kerfur-Omega Complete Manual",
    ["kerfurobook"]            = "Kerfur-Omega Documents Binder",
    ["kerfsp_0"]               = "Omega AI Module",
    ["JAx58b1uDzv5qcsC-PNbSA"] = "Buried Radioactive Capsule",
    ["rad"]                    = "Crafted Radioactive Capsule",

    ["UrzRg8hZONtdBjAw6AeDdA"] = "Bowtie 1",
    ["0BVJlx2tSIDp7tI-5pY9Fg"] = "Bowtie 2",
    ["mCLzJNVkgL95WzQZS4A1DQ"] = "Glasses 1",
    ["ZLNicR39Yw6nfcpqIqTOMQ"] = "Glasses 2",
    ["L9ZpBl83syVPwUcWtiKrmA"] = "Jacket 1",
    ["NNscqUcRdPqM155EkVivmw"] = "Jacket 2",
    ["hCxt6-EcwcEjSaMhNcB9GA"] = "Badge 1",
    ["oYk54e4oDJh5tByJhjXkkg"] = "Badge 2",

    ["0FDYWvOAvoMu6mkGVanVBA"] = "Alpha Toolbox",
    ["vVZg8phEVRRxPxYAYoU2Cw"] = "Hole Toolbox",
    ["QyPfxyhodBwqmXWba-ajDg"] = "Green Hatch Toolbox",
    ["w6BvAMDTkKrebDK8-WDF-g"] = "Deer Skull",
    ["medkit"]                 = "Medkit",
    ["physmodule_spectrogram"] = "Spectogram Module",
    ["carKeys"]                = "Car Keys",
    ["cookingbook"]            = "Cooking Book",
    ["ctf_sYrnBTduGB024LSwfw"] = "Miniature Gas Can",
    ["fishmanbox"]             = "Fisherman's Treasure",
    ["rad_d"]                  = "Geiger Counter",
    ["emfdetec"]               = "EMF Detector",
    ["xqoEV-iC_h61_DPemSGRnA"] = "ATV Wheel",
    ["nKK9Fn-ZOMVO0eEYrPEUCg"] = "TR1 Watering Can",
    ["5fBZsGPS39vtVjCSDG3Hcg"] = "TR1 Lighter",
    ["ZDbeOh-1kddouStQXvJx7g"] = "TR1 Cigarettes",
    ["l8v0YdID0XDsIm7wq2hXRw"] = "TR1 Tinfoil Hat",
    ["0glxPzH2xi3jtFpLO9DUtA"] = "TR1 Toolbox",
    ["sFkwrOE0ls3E-T8uzppeBg"] = "TR1 Gas Welder 1",
    ["tUxNbF2KNwm2Nk-ldIEZgw"] = "TR1 Gas Welder 2",
    ["R4AJ_uGo7nZEWojdtVfgJQ"] = "TR1 Broom",
    ["eO1DVk98mItSzdthKXWXTg"] = "TR2 Watering Can",
    ["Unc4ExtqttNu_KJvveiZng"] = "TR2 Car Battery Charger",
    ["PAPaB9YRWsIynwzVuf9KQQ"] = "TR2 Shovel",
    ["SK14VXC6-B95rDpMUEs2Cw"] = "TR3 Watering Can",
    ["r4PRufgFd4KoFCUiCmMV-Q"] = "TR3 Hiking Boots",
    ["NJMvoxstuzMRl9QmxB2jzA"] = "TR3 Cat Bed",
    ["5Ay4fEhJCLVl38BgIa2QhQ"] = "Security Booth Shovel",
    ["QkA1tJClV58cVYeOFVQMuQ"] = "Abandoned Shack Shovel",
    ["ybDX_iWRl9OmRwr67IFzvg"] = "Stonehenge Shovel",
    ["d7j6lkuG9rIHWpyXEFuHSA"] = "Hole Gas Welder",
    ["VvsuJMi3Bbn0rfW12bIMQA"] = "Well Hook 1",
    ["EMjUBaWgzdolXRqj-Jt7cw"] = "Well Hook 2",
    ["lamp"]                   = "Lantern",
    ["Ogy2hSHlugscjEgf6FG5xw"] = "Radioactive Capsule Blueprint",
    ["t1aTxOgJ7J7rhxlo1yFvMw"] = "Bike Helmet",
    ["_peaGTh2lZ6AVxISqYmr7w"] = "Jar of Honey",
    ["TNhJ5bUJsvfbyCLirNuXug"] = "Compost Bucket 1",
    ["-JbLMGZFFof4Co8BGTqIuA"] = "Compost Bucket 2",
    ["reginald"]               = "Buried Cacti",
    ["wallclocks"]             = "Wall Clock",
    ["massive_limestone_cube"] = "Limestone Slab",
    ["seedp_t"]                = "Seed Pack (The Thingy)",
    ["rifle"]                  = "Old Rifle",
    ["axe"]                    = "Axe",
    ["pickaxe"]                = "Pickaxe",
    ["argemug"]                = "Argemia Mug",
    ["leadpipe"]               = "Lead Pipe",
    ["bryn"]                   = "Unknown Fruit",
    ["ammo"]                   = "Ammo Box",
    ["K0hOWVewmjDiHmHi9qe6Og"] = "Alpha Broom",
    ["pipebomb"]               = "Pipebomb",
    ["VzS8-DlImVtm_QLFeBj6Pw"] = "Sponge",
    ["zti4TWJU3FkU_O9GHbOTPQ"] = "Alpha Fuse 1",
    ["hn1ldlcqPY9qFkk5QkjE0A"] = "Alpha Fuse 2",
    ["0Q1fhyS_haJuVLKUayI2fw"] = "Alpha Fuse 3",
    ["6l784OraV6hMy3ihithBuA"] = "TR1 Fuse",
    ["uncZVSZUVWIAB7v0O8Z3Gg"] = "TR2 Fuse",
    ["3TpBhaLAdNwObtmhH1YIng"] = "TR3 Fuse",
    ["xSWbKp4Pw0Dquk4zkYP8Vg"] = "Forest Fuse 1",
    ["kQsPWWmeQzSwgq_wxqNaAA"] = "Forest Fuse 2",
    ["G70GTAVq_a9FtESqLq529A"] = "Forest Fuse 3",
    ["QIYFQkkv_7cLyNOfY8_Vkg"] = "Forest Fuse 4",
    ["HY239XfybWmdOaysD3KXaw"] = "Hole Welding Mask",
    ["DV1koGZTwQnqy4hiFeWs4A"] = "Green Hatch Welding Mask",
    ["ff_htrophy_0"]           = "Boar Trophy Head",
    ["ff_htrophy_1"]           = "Deer Trophy Head",
    ["ff_htrophy_2"]           = "Goat Trophy Head",
    ["rLt3NxFnKUisbdNTqVioVg"] = "Buried Drive Box",

    ["slab_0"]                 = "Fire Tablet",
    ["slab_1"]                 = "Air Tablet",
    ["slab_2"]                 = "Water Tablet",
    ["slab_3"]                 = "Earth Tablet",
    ["rune_2"]                 = "Fire Rune",
    ["rune_0"]                 = "Air Rune",
    ["rune_3"]                 = "Water Rune",
    ["rune_1"]                 = "Earth Rune",
    ["ritualKnife"]            = "Ritual Knife",

    ["dingus"]                 = "Maxwell",
    ["argemwell"]              = "Argemwell",
    ["gnarpwell"]              = "Gnarpwell",
    ["eriewell"]               = "Eriewell",
    ["kerfoout_maid"]          = "Maid Outfit",
    ["llama"]                  = "Llama Plush",
    ["thiccfus"]               = "Thiccfus Plush"
}
inverse_locations = table_invert(locationKeys)

preserve_items = {
    ["dingus"] = true,
    ["argemwell"] = true,
    ["gnarpwell"] = true,
    ["eriewell"] = true
}
lock_until_ap_item = {
    -- Generated
    ["rune_0"] = true,
    ["rune_1"] = true,
    ["rune_2"] = true,
    ["rune_3"] = true,
    ["fuse"] = true,
    ["rad"] = true,
    ["moniquePlush"] = true,
    ["pipebomb"] = true,
    ["pipebomb"] = true,
    ["argemia_9"] = true,
    ["argemia_10"] = true,
    ["argemia_11"] = true,

    -- In containers
    ["kerfsp_0"] = true,
    ["physmodule_spectrogram"] = true
}

createdGoals = {
    ["/Game/objects/prop_kerfurOmega_0.prop_kerfurOmega_0_C"] = 0, -- Kerfur-Omega
    ["/Game/objects/prop_h.prop_h_C"] = 1, -- Hell Rock
    ["/Game/objects/prop_argw.prop_argw_C"] = 2, -- White Argemia Plush
    ["/Game/objects/prop_argbl.prop_argbl_C"] = 3, -- Black Argemia Plush
    ["/Game/objects/prop_lambert.prop_lambert_C"] = 4 -- Lambert Plush
}
